---
title: "CPR Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r loading, include = FALSE, echo = FALSE}
library("tidyverse")
library("XML")
```

Manifesto goes here

```{r data, echo = FALSE, include=FALSE}
arrest.data <- xmlParse("CPR summary report.xml") %>%
  xmlToDataFrame(stringsAsFactors = FALSE) %>%
  as_tibble()

rate <- as.numeric(arrest.data$CompressionRate)

ratio <- as.numeric(arrest.data$CompressionsRatio)

paused <- as.numeric(arrest.data$LongestPause)

shocks <- as.integer(arrest.data$NumberOfShocks)
```

## Data Summary

Compression rate:
```{r rate, echo = FALSE, warning = FALSE}
summary(rate)
qplot(rate, binwidth = 5)
```

Compression ratio:
```{r ratio, echo = FALSE, warning = FALSE}
summary(ratio)
qplot(ratio, binwidth = 5)
```

Longest pause:
```{r pauses, echo = FALSE, warning = FALSE}
summary(paused)
qplot(paused, binwidth = 30)
```

Number of Defibrillations:
```{r shock, echo = FALSE, warning = FALSE}
summary(shocks)
qplot(shocks, binwidth = 1)
```
